name = "FDF Modular Pack"
prefix = "kar_fdf"
author = "Kartsa"
mainprefix = "x"

[version]
git_hash = 0 

[files]
include = [
    "mod.cpp",
    "data/**",
]

[hemtt.build]
pdrive = "require"

[hemtt.check]
pdrive = "require"

[binarize]
enabled = true 

[lint.sqf]
enabled = true

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE
    "2369477168", # Advanced tool thing
    "843425103", # RHS AFRF Workshop ID
    "843577117", # RHS USAF Workshop ID
    "843593391", # RHS GREF Workshop ID
    "843632231", # RHS SAF  Workshop ID
]

parameters = [
    "-cpuCount=6",
]
file_patching = false # Default: true
binarize = true # Default: false


[hemtt.launch.all]
extends = "default"
workshop = [
    "366425329", #FIR AWS(AirWeaponSystem)
    "1849091860", #FA-18 Hornet
    "1663110214", #F-35C Lightning II
    "826911897", #SFP: Swedish Forces Pack
    "917042703", #SFP: Finnish Forces Pack
    "909320014", #HAFM
    "541888371", #CUP Vehicles
    "497660133", #CUP Weapons
    "497661914", #CUP Units
]


[hemtt.release]
folder = "fdf_modular_faction_pack"
