class CfgVehicles {
	class sfp_patgb203;
	class KAR_FDF_PGB203: sfp_patgb203 {	
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_C";
		displayName = "Pasi";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_PGB203.jpg";
		editorSubcategory = "KAR_FDF_APCs";
		faction = "KAR_FIN_FACTION";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"\sfp_patgb203\data\patgb203_main_co.paa","logo"};
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_APCs";
	};
	class sfp_patgb360;
	class KAR_FDF_PGB360: sfp_patgb360 {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_S";
		displayName = "Patria XA-203";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_PGB360.jpg";
		editorSubcategory = "KAR_FDF_APCs";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_APCs";
	};
	class ffp_md500;
	class KAR_FDF_MD500: ffp_md500 {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_Heli_Pilot";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_md500.jpg";
		editorSubcategory = "KAR_FDF_HELI";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_HELI";
	};
	class ffp_nh90;
	class KAR_FDF_NH90: ffp_nh90 {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_Heli_Pilot";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_NH90.jpg";
		editorSubcategory = "KAR_FDF_HELI";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_HELI";
	};
	class ffp_nh90_armed;
	class KAR_FDF_NH90_A: ffp_nh90_armed {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_Heli_Pilot";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_NH90_A.jpg";
		editorSubcategory = "KAR_FDF_HELI";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_HELI";
	};
	class ffp_rsrakh06;
	class KAR_FDF_FFP_RSRAKH06: ffp_rsrakh06 {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_C_TD";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_FFP_RSRAKH06.jpg";
		editorSubcategory = "KAR_FDF_ART";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_ART";
	};
	class ffp_122h63;
	class KAR_FDF_FFP_122H63: ffp_122h63 {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_C";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_FFP_122H63.jpg";
		editorSubcategory = "KAR_FDF_ART";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_ART";
	};
	class ffp_bmp2;
	class KAR_FDF_FFP_BMP2: ffp_bmp2 {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_C_TD";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_FFP_BMP2.jpg";
		editorSubcategory = "KAR_FDF_APCs";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_APCs";
	};
	class ffp_bmp2_atgm;
	class KAR_FDF_FFP_BMP2_ATGM: ffp_bmp2_atgm {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_C_TD";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_FFP_BMP2_ATGM.jpg";
		editorSubcategory = "KAR_FDF_APCs";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_APCs";
	};
	class ffp_gruppbat;
	class KAR_FDF_FFP_GBOAT: ffp_gruppbat {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_C";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_FFP_GBOAT.jpg";
		editorSubcategory = "KAR_FDF_BOAT";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_BOAT";
	};
	class ffp_bv206;
	class KAR_FDF_FFP_BV206: ffp_bv206 {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_C";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_FFP_BV206.jpg";
		editorSubcategory = "KAR_FDF_Cars";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_Cars";
	};
	class ffp_van_ambulance;
	class KAR_FDF_FFP_AMB: ffp_van_ambulance {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_C";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_FFP_AMB.jpg";
		editorSubcategory = "KAR_FDF_Cars";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_Cars";
	};
	class ffp_rg32m_gmg;
	class KAR_FDF_FFP_RG32_GMG: ffp_rg32m_gmg {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_S";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_FFP_RG32_GMG.jpg";
		editorSubcategory = "KAR_FDF_MRAPs";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_MRAPs";
	};
	class ffp_rg32m;
	class KAR_FDF_FFP_RG32: ffp_rg32m {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_S";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_FFP_RG32.jpg";
		editorSubcategory = "KAR_FDF_MRAPs";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_MRAPs";
	};
	class ffp_orbiter;
	class KAR_FDF_FFP_Orbiter: ffp_orbiter {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "B_UAV_AI";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_FFP_ORBITER.jpg";
		editorSubcategory = "KAR_FDF_Drones";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_Drones";
	};
	class ffp_leopard2a4;
	class KAR_FDF_FFP_LEO2A4: ffp_leopard2a4 {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_C_TD";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_FFP_LEO2A4.jpg";
		editorSubcategory = "KAR_FDF_Tanks";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_Tanks";
	};
	class ffp_leopard2a6;
	class KAR_FDF_FFP_LEO2A6: ffp_leopard2a6 {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_C_TD";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_FFP_LEO2A6.jpg";
		editorSubcategory = "KAR_FDF_Tanks";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_Tanks";
	};
	class ffp_ito2005m;
	class KAR_FDF_FFP_ITO05: ffp_ito2005m {
		class TransportItems {};
		class TransportMagazines {};
		class TransportWeapons {};
		crew = "KAR_FDF_RIF_C";
		editorCategory = "KAR_FDF_TOP";
		editorPreview = "\KAR_FDF_EP\UI\KAR_FDF_FFP_ITO05.jpg";
		editorSubcategory = "KAR_FDF_TUR";
		faction = "KAR_FIN_FACTION";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		vehicleclass = "KAR_FDF_TUR";
	};
};